### PR TITLE
Updating Terminal

### PR DESCRIPTION
**Pull request by Guchii**
- Removed obsolete/deprecated apps 
    - termite
    - upterm
- Added kitty and st.

### CODE REVIEW

**Comment by Guchii** [comment]
@harrytran103 I was added as an assignee. What should I do now to get my PR merged? can you please guide me?

**Comment by harrytran103** [comment]
@Guchii I want you to sort the app names in ascending order.
Example:
- Kitty
- ...
- Tilda
- Tilix

**Comment by harrytran103** [comment]
The deprecated apps only archived, it's still valuable

**Comment by harrytran103** [comment]
@Guchii thank bro for your amazing PRs

**Review by harrytran103 — APPROVED** [review]
done

**Pull request merged**
